{% set name = "contourpy" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/contourpy-{{ version }}.tar.gz
  sha256: dfd97abd83335045a913e3bcc4a09c0ceadbe66580cf573fe961f4a825efa699

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  missing_dso_whitelist:  # [s390x]
    - $RPATH/ld64.so.1    # [s390x]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - meson >=1.2.0
    - pybind11 >=2.13.2,!=2.13.3
    - python
    - meson-python >=0.13.1
  run:
    - python
    - numpy >=1.23

test:
  imports:
    - contourpy
    - contourpy.util
  commands:
    - pip check
    - python -c "import contourpy as c; print(c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9))"
    - python -c "from contourpy.util import build_config; from pprint import pprint; pprint(build_config())"
    - python -c "import platform, sys; print(sys.version, platform.uname())"
  requires:
    - pip

about:
  home: https://github.com/contourpy/contourpy
  summary: Python library for calculating contours of 2D quadrilateral grids.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral
    grids.  It is written in C++11 and wrapped using pybind11.
  doc_url: https://contourpy.readthedocs.io
  dev_url: https://github.com/contourpy/contourpy

extra:
  recipe-maintainers:
    - ianthomas23
