{% set name = "contourpy" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/contourpy-{{ version }}.tar.gz
  sha256: 083e12155b210502d0bca491432bb04d56dc3432f95a979b429f2848c3dbe880

build:
  number: 0
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports:
    - libcxx

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - meson >=1.2.0
    - meson-python >=0.13.1
    - pybind11 >=2.13.2,!=2.13.3
  run:
    - python
    - numpy >=1.25

test:
  source_files:
    - tests
  imports:
    - contourpy
    - contourpy.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest
    - matplotlib
    - pillow
    - wurlitzer

about:
  home: https://github.com/contourpy/contourpy
  summary: Python library for calculating contours of 2D quadrilateral grids.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral
    grids.  It is written in C++11 and wrapped using pybind11.
  doc_url: https://contourpy.readthedocs.io
  dev_url: https://github.com/contourpy/contourpy

extra:
  recipe-maintainers:
    - ianthomas23
