{% set name = "contourpy" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/contourpy-{{ version }}.tar.gz
  sha256: 20156f5a1ac4f8ce02656e39a61e82164a3d359796dc8026f75b062783d500e1

build:
  number: 0
  skip: true  # [py<312]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - meson >=1.2.0
    - meson-python >=0.18.0
    - pybind11 >=2.13.2,!=2.13.3
  run:
    - python
    - numpy >=2.0
  run_constrained:
    - mypy ==2.1.0

test:
  source_files:
    - tests
  imports:
    - contourpy
    - contourpy.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest
    - matplotlib
    - pillow
    - wurlitzer  # [unix]

about:
  home: https://github.com/contourpy/contourpy
  summary: Python library for calculating contours of 2D quadrilateral grids.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    ContourPy is a Python library for calculating contours of 2D quadrilateral
    grids.  It is written in C++11 and wrapped using pybind11.
  doc_url: https://contourpy.readthedocs.io
  dev_url: https://github.com/contourpy/contourpy

extra:
  recipe-maintainers:
    - ianthomas23
